### ISSUE TITLE
tinkerpop2/pom.xml is missing sonatype repository

### ISSUE THREAD

**Issue by tm-robinson** [thinkaurelius/neo4j-gremlin-plugin#11]
The following needs to be added to tinkerpop2/pom.xml to enable the plugin to build successfully:

    <repositories>
        <repository>
            <id>Sonatype repository</id>
            <name>Sonatype's Maven repository</name>
            <url>http://oss.sonatype.org/content/groups/public</url>
        </repository>
    </repositories>

This is already present in tinkerpop3/pom.xml but is missing from tinkerpop2/pom.xml

**Comment by dkuppitz** [comment]
I will probably get rid of TP2 in the next release.
