### ISSUE TITLE
Can't get to work with my Neo4j 2.1.5 CE

### ISSUE THREAD

**Issue by fancellu** [thinkaurelius/neo4j-gremlin-plugin#3]
Following instructions as per

https://github.com/thinkaurelius/neo4j-gremlin-plugin

I download the tp3 rel from https://github.com/thinkaurelius/neo4j-gremlin-plugin/releases

Unzip to my plugin dir

Put the following in neo4j-server.properties

org.neo4j.server.thirdparty_jaxrs_classes=com.thinkaurelius.neo4j.plugins=/tp

Start up Neo4j. But it doesn't see it

localhost:7474/db/data/

No extensions seen.

Any idea why?

I see this in my log

INFO: Scanning for root resource and provider classes in the packages:
  com.thinkaurelius.neo4j.plugins
Nov 03, 2014 8:35:37 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class com.thinkaurelius.neo4j.plugins.GremlinPlugin
Nov 03, 2014 8:35:37 PM com.sun.jersey.api.core.ScanningResourceConfig init
INFO: No provider classes found.

Thanks.

**Comment by SundialServices** [comment]
You should re-open this issue.  If you run "neo4j console" you can see a traceback.  Will open another issue to describe what I am seeing.
