### ISSUE TITLE
How to keep loaded graph in memory

### ISSUE THREAD

**Issue by NitinJamadagni** [thinkaurelius/neo4j-gremlin-plugin#6]
Hey,
How does the "load" exactly work?
Let's say I issue a curl request with a gremlin script where I load the given script.

     curl -s -G --data-urlencode 'script=constructgraph()' --data-urlencode 'load=trial_load_users' http://localhost:7474/tp/gremlin/execute

Script:::

             g= new Neo4j2Graph('/home/nitin/Desktop/MINOR_PROJECT/neo4j-community-2.1.7/data/user_appl.db')
          
            def constructgraph()
           {
	          g.addVertex([identity:"kkns1",gender:"male"]);
                  g.addVertex([identity:"kkns2",gender:"male"]);
                  g.addVertex([identity:"kkns3",gender:"male"]);
                  g.addVertex([identity:"kkns4",gender:"female"]);
                  g.addVertex([identity:"kkns5",gender:"male"]);
                  g.V.has('identity').sideEffect({it.weight=0});
                  g.addVertex([appname:"VLC",genre:"player"]);
                  g.addVertex([appname:"Eclipse",genre:"IDE"]);
                  g.addVertex([appname:"NetBeans",genre:"IDE"]);
                  g.addVertex([appname:"XChat",genre:"IRC"]);
                  g.addVertex([appname:"TPA",genre:"none"]);
                  g.V.has("identity","kkns1").next().addEdge("uses",g.V.has("appname","VLC").next());
                  g.V.has("identity","kkns1").next().addEdge("uses",g.V.has("appname","Eclipse").next());
                  g.V.has("identity","kkns2").next().addEdge("uses",g.V.has("appname","VLC").next());
                  g.V.has("identity","kkns2").next().addEdge("uses",g.V.has("appname","Eclipse").next());
	          g.V.has("identity","kkns2").next().addEdge("uses",g.V.has("appname","XChat").next());
	          g.V.has("identity","kkns3").next().addEdge("uses",g.V.has("appname","VLC").next());
	          g.V.has("identity","kkns3").next().addEdge("uses",g.V.has("appname","TPA").next());
	         g.V.has("identity","kkns3").next().addEdge("uses",g.V.has("appname","NetBeans").next());
	         g.V.has("identity","kkns4").next().addEdge("uses",g.V.has("appname","NetBeans").next());
	         g.V.has("identity","kkns4").next().addEdge("uses",g.V.has("appname","TPA").next());
	         g.V.has("identity","kkns5").next().addEdge("uses",g.V.has("appname","Eclipse").next());
	         g.E.sideEffect{it.weight=1}
	         g.V.map;
	         g.E;
           }
          

           def display()
           {
	          g.V.map;
           }

It writes fine to the .db file,but on the next curl request where I call display() it does not display the map of the vertices.

     curl -s -G --data-urlencode 'script=display()' --data-urlencode 'load=trial_load_users' http://localhost:7474/tp/gremlin/execute

How does the plugin work,does it spawn one gremlin shell and take curl requests?
How do I keep the g variable in memory,so that I can write different scripts to do different functions on the graph in memory and save the graph later?

**Comment by dkuppitz** [comment]
> `g= new Neo4j2Graph('/home/nitin/...`

You shouldn't do that. The graph variable `g` is always available and provided by the Neo4j Server.
See the samples at:

https://github.com/thinkaurelius/neo4j-gremlin-plugin#interacting-with-the-graph

**Comment by NitinJamadagni** [comment]
@dkuppitz  :Thanks, I think i get it now!
