### ISSUE TITLE
Gremlin script only partially executed

### ISSUE THREAD

**Issue by NitinJamadagni** [thinkaurelius/neo4j-gremlin-plugin#7]
I am trying to add an edge if it does not exist , else update it's weight

             new File("apps.txt").eachLine { line ->
    		vno=g.V.has("appname",line).next().id;
    		g.v(vno)_().ifThenElse{it.in("uses").has("identity",identity).count()==0}{g.addEdge(g.v(userno), it, "uses").sideEffect{it.weight=1}.iterate()}{g.v(vno).inE("uses").outV.has("identity",identity).back(2).sideEffect{it.weight=it.weight+1}.iterate()};
			
	}

Apparently only the last app read by line closure,it's edge is getting updated

**Comment by dkuppitz** [comment]
Why do you think that this problem is related to the plugin?

**Comment by NitinJamadagni** [comment]
Hey,
I think the issue it's with the plugin because on a gremlin repl shell
using the TinkerGraph() it works just fine.But when run by making a curl
request to the neo4j server with the plugin the results don't get logged(I
checked the neo4j console logs as well)

Thanks
Nitin

**Comment by dkuppitz** [comment]
I don't think that this problem is caused by the plugin. Note that the REPL iterates your Gremlin pipeline automatically - in any other scenario you'll need to take care of it. Your pipeline is simply not iterated. Add `.iterate()` to your last statement or simply use this:

```groovy
new File("apps.txt").eachLine { def line ->
    g.V().has("appname", line).sideEffect { def app ->
        def pipe = app.in("uses").has("identity", identity)
        if (pipe.hasNext()) {
            app.setProperty("weight", app.getProperty("weight") + 1)
        } else {
            g.v(userno).addEdge("uses", app, ["weight": 1])
        }
    }.iterate()
}
```

**Comment by NitinJamadagni** [comment]
Thanks Daniel,
It worked after a .iterate() at the end.
Should have read clearly about ->* REPL iterating the pipeline
automatically and we having to take care of it in any other case*.

Thanks
Nitin Jamadagni
